# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_date', models.DateField()),
                ('meet_time', models.TimeField()),
                ('lift_name', models.CharField(max_length=200)),
                ('lift_terminal', models.CharField(max_length=200)),
                ('notes_text', models.CharField(max_length=200)),
            ],
        ),
    ]
