# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meet_name',
            field=models.CharField(default='Test', max_length=200),
        ),
    ]
