# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0004_auto_20160706_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldborder',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
