# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0005_auto_20160706_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
