# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0007_worldborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='lift_name',
            field=models.CharField(choices=[('BROOKS', 'Brooks'), ('HOGSBACK', 'Hogsback'), ('SKYLINE', 'Skyline')], max_length=200),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='lift_terminal',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom')], max_length=200),
        ),
    ]
