# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0008_auto_20160706_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 10, 18, 26, 5, 75000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
