# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0009_meetup_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='lat',
            field=models.FloatField(default='47.734230'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='lon',
            field=models.FloatField(default='-121.086300'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='lift_name',
            field=models.CharField(choices=[('BROOKS', 'Brooks'), ('HOGSBACK', 'Hogsback'), ('SKYLINE EXPRESS', 'Skyline'), ('DAISY', 'Daisy'), ('KEHRS CHAIR', 'Kehrs Chair'), ('TYE MILL', 'Tye Mill'), ('DOUBLE DIAMOND', 'Double Diamond'), ('7TH HEAVEN', '7th Heaven'), ('JUPITER EXPRESS', 'Jupiter Express'), ('SOUTHERN CROSS', 'Southern Cross')], max_length=200),
        ),
    ]
