# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0010_auto_20160710_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='lift_terminal',
            field=models.CharField(choices=[('TOP', 'Top'), ('BOT', 'Bottom')], max_length=200),
        ),
    ]
