# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruisertime', '0011_auto_20160715_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='lift_terminal',
            field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('BOT', 'Bottom')], max_length=200),
        ),
    ]
